version: "3.9"

services:
  db:
    image: postgres:15.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: "go_walk_db"
      POSTGRES_USER: "go_walk_user"
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbroot/init.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U go_walk_user -d go_walk_db'"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: ./tgbot
    restart: unless-stopped
    depends_on:
      - db
    command: sh -c "/wait && dotnet ConsoleAppGoWalkTgBot.dll"
    # volumes:
    #   - ./bot/logs:/root/logs
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5

